# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T11:44:28+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class BadRequestException(RootModel[Any]):
    root: Any


class BulkDeploymentStatus(Enum):
    Initializing = 'Initializing'
    Running = 'Running'
    Completed = 'Completed'
    Stopping = 'Stopping'
    Stopped = 'Stopped'
    Failed = 'Failed'


class ConfigurationSyncStatus(Enum):
    InSync = 'InSync'
    OutOfSync = 'OutOfSync'


class CreateGroupCertificateAuthorityRequest(BaseModel):
    pass


class DeleteConnectorDefinitionRequest(BaseModel):
    pass


class DeleteConnectorDefinitionResponse(BaseModel):
    pass


class DeleteCoreDefinitionRequest(BaseModel):
    pass


class DeleteCoreDefinitionResponse(BaseModel):
    pass


class DeleteDeviceDefinitionRequest(BaseModel):
    pass


class DeleteDeviceDefinitionResponse(BaseModel):
    pass


class DeleteFunctionDefinitionRequest(BaseModel):
    pass


class DeleteFunctionDefinitionResponse(BaseModel):
    pass


class DeleteGroupRequest(BaseModel):
    pass


class DeleteGroupResponse(BaseModel):
    pass


class DeleteLoggerDefinitionRequest(BaseModel):
    pass


class DeleteLoggerDefinitionResponse(BaseModel):
    pass


class DeleteResourceDefinitionRequest(BaseModel):
    pass


class DeleteResourceDefinitionResponse(BaseModel):
    pass


class DeleteSubscriptionDefinitionRequest(BaseModel):
    pass


class DeleteSubscriptionDefinitionResponse(BaseModel):
    pass


class DeploymentType(Enum):
    NewDeployment = 'NewDeployment'
    Redeployment = 'Redeployment'
    ResetDeployment = 'ResetDeployment'
    ForceResetDeployment = 'ForceResetDeployment'


class DisassociateRoleFromGroupRequest(BaseModel):
    pass


class DisassociateServiceRoleFromAccountRequest(BaseModel):
    pass


class EncodingType(Enum):
    binary = 'binary'
    json = 'json'


class FunctionIsolationMode(Enum):
    GreengrassContainer = 'GreengrassContainer'
    NoContainer = 'NoContainer'


class GetAssociatedRoleRequest(BaseModel):
    pass


class GetBulkDeploymentStatusRequest(BaseModel):
    pass


class GetConnectivityInfoRequest(BaseModel):
    pass


class GetConnectorDefinitionRequest(BaseModel):
    pass


class GetConnectorDefinitionVersionRequest(BaseModel):
    pass


class GetCoreDefinitionRequest(BaseModel):
    pass


class GetCoreDefinitionVersionRequest(BaseModel):
    pass


class GetDeploymentStatusRequest(BaseModel):
    pass


class GetDeviceDefinitionRequest(BaseModel):
    pass


class GetDeviceDefinitionVersionRequest(BaseModel):
    pass


class GetFunctionDefinitionRequest(BaseModel):
    pass


class GetFunctionDefinitionVersionRequest(BaseModel):
    pass


class GetGroupCertificateAuthorityRequest(BaseModel):
    pass


class GetGroupCertificateConfigurationRequest(BaseModel):
    pass


class GetGroupRequest(BaseModel):
    pass


class GetGroupVersionRequest(BaseModel):
    pass


class GetLoggerDefinitionRequest(BaseModel):
    pass


class GetLoggerDefinitionVersionRequest(BaseModel):
    pass


class GetResourceDefinitionRequest(BaseModel):
    pass


class GetResourceDefinitionVersionRequest(BaseModel):
    pass


class GetServiceRoleForAccountRequest(BaseModel):
    pass


class GetSubscriptionDefinitionRequest(BaseModel):
    pass


class GetSubscriptionDefinitionVersionRequest(BaseModel):
    pass


class GetThingRuntimeConfigurationRequest(BaseModel):
    pass


class InternalServerErrorException(RootModel[Any]):
    root: Any


class ListBulkDeploymentDetailedReportsRequest(BaseModel):
    pass


class ListBulkDeploymentsRequest(BaseModel):
    pass


class ListConnectorDefinitionVersionsRequest(BaseModel):
    pass


class ListConnectorDefinitionsRequest(BaseModel):
    pass


class ListCoreDefinitionVersionsRequest(BaseModel):
    pass


class ListCoreDefinitionsRequest(BaseModel):
    pass


class ListDeploymentsRequest(BaseModel):
    pass


class ListDeviceDefinitionVersionsRequest(BaseModel):
    pass


class ListDeviceDefinitionsRequest(BaseModel):
    pass


class ListFunctionDefinitionVersionsRequest(BaseModel):
    pass


class ListFunctionDefinitionsRequest(BaseModel):
    pass


class ListGroupCertificateAuthoritiesRequest(BaseModel):
    pass


class ListGroupVersionsRequest(BaseModel):
    pass


class ListGroupsRequest(BaseModel):
    pass


class ListLoggerDefinitionVersionsRequest(BaseModel):
    pass


class ListLoggerDefinitionsRequest(BaseModel):
    pass


class ListResourceDefinitionVersionsRequest(BaseModel):
    pass


class ListResourceDefinitionsRequest(BaseModel):
    pass


class ListSubscriptionDefinitionVersionsRequest(BaseModel):
    pass


class ListSubscriptionDefinitionsRequest(BaseModel):
    pass


class ListTagsForResourceRequest(BaseModel):
    pass


class LoggerComponent(Enum):
    GreengrassSystem = 'GreengrassSystem'
    Lambda = 'Lambda'


class LoggerLevel(Enum):
    DEBUG = 'DEBUG'
    INFO = 'INFO'
    WARN = 'WARN'
    ERROR = 'ERROR'
    FATAL = 'FATAL'


class LoggerType(Enum):
    FileSystem = 'FileSystem'
    AWSCloudWatch = 'AWSCloudWatch'


class Permission(Enum):
    ro = 'ro'
    rw = 'rw'


class S3UrlSignerRole(RootModel[str]):
    root: str = Field(
        ...,
        description='The IAM Role that Greengrass will use to create pre-signed URLs pointing towards the update artifact.',
    )


class SoftwareToUpdate(Enum):
    core = 'core'
    ota_agent = 'ota_agent'


class StopBulkDeploymentRequest(BaseModel):
    pass


class StopBulkDeploymentResponse(BaseModel):
    pass


class Telemetry(Enum):
    On = 'On'
    Off = 'Off'


class TelemetryConfiguration(BaseModel):
    ConfigurationSyncStatus_1: Optional[ConfigurationSyncStatus] = Field(
        None, alias='ConfigurationSyncStatus'
    )
    Telemetry_1: Telemetry = Field(..., alias='Telemetry')


class TelemetryConfigurationUpdate(BaseModel):
    Telemetry_1: Telemetry = Field(..., alias='Telemetry')


class UntagResourceRequest(BaseModel):
    pass


class UpdateAgentLogLevel(Enum):
    NONE = 'NONE'
    TRACE = 'TRACE'
    DEBUG = 'DEBUG'
    VERBOSE = 'VERBOSE'
    INFO = 'INFO'
    WARN = 'WARN'
    ERROR = 'ERROR'
    FATAL = 'FATAL'


class UpdateConnectorDefinitionResponse(BaseModel):
    pass


class UpdateCoreDefinitionResponse(BaseModel):
    pass


class UpdateDeviceDefinitionResponse(BaseModel):
    pass


class UpdateFunctionDefinitionResponse(BaseModel):
    pass


class UpdateGroupResponse(BaseModel):
    pass


class UpdateLoggerDefinitionResponse(BaseModel):
    pass


class UpdateResourceDefinitionResponse(BaseModel):
    pass


class UpdateSubscriptionDefinitionResponse(BaseModel):
    pass


class UpdateTargetsArchitecture(Enum):
    armv6l = 'armv6l'
    armv7l = 'armv7l'
    x86_64 = 'x86_64'
    aarch64 = 'aarch64'


class UpdateTargetsOperatingSystem(Enum):
    ubuntu = 'ubuntu'
    raspbian = 'raspbian'
    amazon_linux = 'amazon_linux'
    openwrt = 'openwrt'


class UpdateThingRuntimeConfigurationRequest(BaseModel):
    TelemetryConfiguration: Optional[TelemetryConfigurationUpdate] = None


class UpdateThingRuntimeConfigurationResponse(BaseModel):
    pass


class FieldBoolean(RootModel[bool]):
    root: bool


class FieldInteger(RootModel[int]):
    root: int


class FieldString(RootModel[str]):
    root: str


class GreengrassBulkDeploymentsPostRequest(BaseModel):
    ExecutionRoleArn: str = Field(
        ...,
        description="The ARN of the execution role to associate with the bulk deployment operation. This IAM role must allow the ''greengrass:CreateDeployment'' action for all group versions that are listed in the input file. This IAM role must have access to the S3 bucket containing the input file.",
    )
    InputFileUri: str = Field(
        ...,
        description="The URI of the input file contained in the S3 bucket. The execution role must have ''getObject'' permissions on this bucket to access the input file. The input file is a JSON-serialized, line delimited file with UTF-8 encoding that provides a list of group and version IDs and the deployment type. This file must be less than 100 MB. Currently, AWS IoT Greengrass supports only ''NewDeployment'' deployment types.",
    )
    tags: Optional[Dict[str, FieldString]] = Field(
        None, description='The key-value pair for the resource tag.'
    )


class GreengrassDefinitionConnectorsConnectorDefinitionIdPutRequest(BaseModel):
    Name: Optional[str] = Field(None, description='The name of the definition.')


class GreengrassDefinitionCoresCoreDefinitionIdPutRequest(BaseModel):
    Name: Optional[str] = Field(None, description='The name of the definition.')


class GreengrassDefinitionDevicesDeviceDefinitionIdPutRequest(BaseModel):
    Name: Optional[str] = Field(None, description='The name of the definition.')


class GreengrassDefinitionFunctionsFunctionDefinitionIdPutRequest(BaseModel):
    Name: Optional[str] = Field(None, description='The name of the definition.')


class GreengrassDefinitionLoggersLoggerDefinitionIdPutRequest(BaseModel):
    Name: Optional[str] = Field(None, description='The name of the definition.')


class GreengrassDefinitionResourcesResourceDefinitionIdPutRequest(BaseModel):
    Name: Optional[str] = Field(None, description='The name of the definition.')


class GreengrassDefinitionSubscriptionsSubscriptionDefinitionIdPutRequest(BaseModel):
    Name: Optional[str] = Field(None, description='The name of the definition.')


class InitialVersion7(BaseModel):
    ConnectorDefinitionVersionArn: Optional[FieldString] = None
    CoreDefinitionVersionArn: Optional[FieldString] = None
    DeviceDefinitionVersionArn: Optional[FieldString] = None
    FunctionDefinitionVersionArn: Optional[FieldString] = None
    LoggerDefinitionVersionArn: Optional[FieldString] = None
    ResourceDefinitionVersionArn: Optional[FieldString] = None
    SubscriptionDefinitionVersionArn: Optional[FieldString] = None


class GreengrassGroupsPostRequest(BaseModel):
    InitialVersion: Optional[InitialVersion7] = Field(
        None, description='Information about a group version.'
    )
    Name: str = Field(..., description='The name of the group.')
    tags: Optional[Dict[str, FieldString]] = Field(
        None, description='The key-value pair for the resource tag.'
    )


class GreengrassGroupsGroupIdPutRequest(BaseModel):
    Name: Optional[str] = Field(None, description='The name of the definition.')


class GreengrassGroupsGroupIdCertificateauthoritiesConfigurationExpiryPutRequest(
    BaseModel
):
    CertificateExpiryInMilliseconds: Optional[str] = Field(
        None,
        description='The amount of time remaining before the certificate expires, in milliseconds.',
    )


class GreengrassGroupsGroupIdDeploymentsPostRequest(BaseModel):
    DeploymentId: Optional[str] = Field(
        None,
        description='The ID of the deployment if you wish to redeploy a previous deployment.',
    )
    DeploymentType_1: DeploymentType = Field(
        ...,
        alias='DeploymentType',
        description="The type of deployment. When used for ''CreateDeployment'', only ''NewDeployment'' and ''Redeployment'' are valid.",
    )
    GroupVersionId: Optional[str] = Field(
        None, description='The ID of the group version to be deployed.'
    )


class GreengrassGroupsGroupIdDeploymentsResetPostRequest(BaseModel):
    Force: Optional[bool] = Field(
        None, description='If true, performs a best-effort only core reset.'
    )


class GreengrassGroupsGroupIdRolePutRequest(BaseModel):
    RoleArn: str = Field(
        ...,
        description='The ARN of the role you wish to associate with this group. The existence of the role is not validated.',
    )


class GreengrassGroupsGroupIdVersionsPostRequest(BaseModel):
    ConnectorDefinitionVersionArn: Optional[str] = Field(
        None, description='The ARN of the connector definition version for this group.'
    )
    CoreDefinitionVersionArn: Optional[str] = Field(
        None, description='The ARN of the core definition version for this group.'
    )
    DeviceDefinitionVersionArn: Optional[str] = Field(
        None, description='The ARN of the device definition version for this group.'
    )
    FunctionDefinitionVersionArn: Optional[str] = Field(
        None, description='The ARN of the function definition version for this group.'
    )
    LoggerDefinitionVersionArn: Optional[str] = Field(
        None, description='The ARN of the logger definition version for this group.'
    )
    ResourceDefinitionVersionArn: Optional[str] = Field(
        None, description='The ARN of the resource definition version for this group.'
    )
    SubscriptionDefinitionVersionArn: Optional[str] = Field(
        None,
        description='The ARN of the subscription definition version for this group.',
    )


class GreengrassServicerolePutRequest(BaseModel):
    RoleArn: str = Field(
        ...,
        description='The ARN of the service role you wish to associate with your account.',
    )


class TelemetryConfiguration1(BaseModel):
    Telemetry_1: Optional[Telemetry] = Field(None, alias='Telemetry')


class GreengrassThingsThingNameRuntimeconfigPutRequest(BaseModel):
    TelemetryConfiguration: Optional[TelemetryConfiguration1] = Field(
        None, description='Configuration settings for running telemetry.'
    )


class GreengrassUpdatesPostRequest(BaseModel):
    S3UrlSignerRole: str = Field(
        ...,
        description='The IAM Role that Greengrass will use to create pre-signed URLs pointing towards the update artifact.',
    )
    SoftwareToUpdate_1: SoftwareToUpdate = Field(
        ...,
        alias='SoftwareToUpdate',
        description='The piece of software on the Greengrass core that will be updated.',
    )
    UpdateAgentLogLevel_1: Optional[UpdateAgentLogLevel] = Field(
        None,
        alias='UpdateAgentLogLevel',
        description='The minimum level of log statements that should be logged by the OTA Agent during an update.',
    )
    UpdateTargets: List[FieldString] = Field(
        ...,
        description='The ARNs of the targets (IoT things or IoT thing groups) that this update will be applied to.',
    )
    UpdateTargetsArchitecture_1: UpdateTargetsArchitecture = Field(
        ...,
        alias='UpdateTargetsArchitecture',
        description='The architecture of the cores which are the targets of an update.',
    )
    UpdateTargetsOperatingSystem_1: UpdateTargetsOperatingSystem = Field(
        ...,
        alias='UpdateTargetsOperatingSystem',
        description='The operating system of the cores which are the targets of an update.',
    )


class TagsResourceArnPostRequest(BaseModel):
    tags: Optional[Dict[str, FieldString]] = Field(
        None, description='The key-value pair for the resource tag.'
    )


class TagKeys(RootModel[List[FieldString]]):
    root: List[FieldString]


class AssociateRoleToGroupRequest(BaseModel):
    RoleArn: FieldString


class AssociateRoleToGroupResponse(BaseModel):
    AssociatedAt: Optional[FieldString] = None


class AssociateServiceRoleToAccountRequest(BaseModel):
    RoleArn: FieldString


class AssociateServiceRoleToAccountResponse(BaseModel):
    AssociatedAt: Optional[FieldString] = None


class BulkDeployment(BaseModel):
    BulkDeploymentArn: Optional[FieldString] = None
    BulkDeploymentId: Optional[FieldString] = None
    CreatedAt: Optional[FieldString] = None


class BulkDeploymentMetrics(BaseModel):
    InvalidInputRecords: Optional[FieldInteger] = None
    RecordsProcessed: Optional[FieldInteger] = None
    RetryAttempts: Optional[FieldInteger] = None


class BulkDeployments(RootModel[List[BulkDeployment]]):
    root: List[BulkDeployment]


class ConnectivityInfo(BaseModel):
    HostAddress: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    Metadata: Optional[FieldString] = None
    PortNumber: Optional[FieldInteger] = None


class Core(BaseModel):
    CertificateArn: FieldString
    Id: FieldString
    SyncShadow: Optional[FieldBoolean] = None
    ThingArn: FieldString


class CreateConnectorDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None


class CreateConnectorDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class CreateCoreDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None


class CreateCoreDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class CreateDeploymentRequest(BaseModel):
    DeploymentId: Optional[FieldString] = None
    DeploymentType_1: DeploymentType = Field(..., alias='DeploymentType')
    GroupVersionId: Optional[FieldString] = None


class CreateDeploymentResponse(BaseModel):
    DeploymentArn: Optional[FieldString] = None
    DeploymentId: Optional[FieldString] = None


class CreateDeviceDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None


class CreateDeviceDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class CreateFunctionDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None


class CreateFunctionDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class CreateGroupCertificateAuthorityResponse(BaseModel):
    GroupCertificateAuthorityArn: Optional[FieldString] = None


class CreateGroupResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None


class CreateGroupVersionRequest(BaseModel):
    ConnectorDefinitionVersionArn: Optional[FieldString] = None
    CoreDefinitionVersionArn: Optional[FieldString] = None
    DeviceDefinitionVersionArn: Optional[FieldString] = None
    FunctionDefinitionVersionArn: Optional[FieldString] = None
    LoggerDefinitionVersionArn: Optional[FieldString] = None
    ResourceDefinitionVersionArn: Optional[FieldString] = None
    SubscriptionDefinitionVersionArn: Optional[FieldString] = None


class CreateGroupVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class CreateLoggerDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None


class CreateLoggerDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class CreateResourceDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None


class CreateResourceDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class CreateSoftwareUpdateJobResponse(BaseModel):
    IotJobArn: Optional[FieldString] = None
    IotJobId: Optional[FieldString] = None
    PlatformSoftwareVersion: Optional[FieldString] = None


class CreateSubscriptionDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None


class CreateSubscriptionDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class Deployment(BaseModel):
    CreatedAt: Optional[FieldString] = None
    DeploymentArn: Optional[FieldString] = None
    DeploymentId: Optional[FieldString] = None
    DeploymentType_1: Optional[DeploymentType] = Field(None, alias='DeploymentType')
    GroupArn: Optional[FieldString] = None


class Deployments(RootModel[List[Deployment]]):
    root: List[Deployment]


class Device(BaseModel):
    CertificateArn: FieldString
    Id: FieldString
    SyncShadow: Optional[FieldBoolean] = None
    ThingArn: FieldString


class DisassociateRoleFromGroupResponse(BaseModel):
    DisassociatedAt: Optional[FieldString] = None


class DisassociateServiceRoleFromAccountResponse(BaseModel):
    DisassociatedAt: Optional[FieldString] = None


class ErrorDetail(BaseModel):
    DetailedErrorCode: Optional[FieldString] = None
    DetailedErrorMessage: Optional[FieldString] = None


class ErrorDetails(RootModel[List[ErrorDetail]]):
    root: List[ErrorDetail] = Field(..., description='A list of error details.')


class FunctionRunAsConfig(BaseModel):
    Gid: Optional[FieldInteger] = None
    Uid: Optional[FieldInteger] = None


class GetAssociatedRoleResponse(BaseModel):
    AssociatedAt: Optional[FieldString] = None
    RoleArn: Optional[FieldString] = None


class GetDeploymentStatusResponse(BaseModel):
    DeploymentStatus: Optional[FieldString] = None
    DeploymentType_1: Optional[DeploymentType] = Field(None, alias='DeploymentType')
    ErrorDetails_1: Optional[ErrorDetails] = Field(None, alias='ErrorDetails')
    ErrorMessage: Optional[FieldString] = None
    UpdatedAt: Optional[FieldString] = None


class GetGroupCertificateAuthorityResponse(BaseModel):
    GroupCertificateAuthorityArn: Optional[FieldString] = None
    GroupCertificateAuthorityId: Optional[FieldString] = None
    PemEncodedCertificate: Optional[FieldString] = None


class GetGroupCertificateConfigurationResponse(BaseModel):
    CertificateAuthorityExpiryInMilliseconds: Optional[FieldString] = None
    CertificateExpiryInMilliseconds: Optional[FieldString] = None
    GroupId: Optional[FieldString] = None


class GetServiceRoleForAccountResponse(BaseModel):
    AssociatedAt: Optional[FieldString] = None
    RoleArn: Optional[FieldString] = None


class GroupCertificateAuthorityProperties(BaseModel):
    GroupCertificateAuthorityArn: Optional[FieldString] = None
    GroupCertificateAuthorityId: Optional[FieldString] = None


class GroupInformation(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None


class GroupOwnerSetting(BaseModel):
    AutoAddGroupOwner: Optional[FieldBoolean] = None
    GroupOwner: Optional[FieldString] = None


class GroupVersion(BaseModel):
    ConnectorDefinitionVersionArn: Optional[FieldString] = None
    CoreDefinitionVersionArn: Optional[FieldString] = None
    DeviceDefinitionVersionArn: Optional[FieldString] = None
    FunctionDefinitionVersionArn: Optional[FieldString] = None
    LoggerDefinitionVersionArn: Optional[FieldString] = None
    ResourceDefinitionVersionArn: Optional[FieldString] = None
    SubscriptionDefinitionVersionArn: Optional[FieldString] = None


class ListBulkDeploymentsResponse(BaseModel):
    BulkDeployments_1: Optional[BulkDeployments] = Field(None, alias='BulkDeployments')
    NextToken: Optional[FieldString] = None


class ListDeploymentsResponse(BaseModel):
    Deployments_1: Optional[Deployments] = Field(None, alias='Deployments')
    NextToken: Optional[FieldString] = None


class LocalDeviceResourceData(BaseModel):
    GroupOwnerSetting_1: Optional[GroupOwnerSetting] = Field(
        None, alias='GroupOwnerSetting'
    )
    SourcePath: Optional[FieldString] = None


class LocalVolumeResourceData(BaseModel):
    DestinationPath: Optional[FieldString] = None
    GroupOwnerSetting_1: Optional[GroupOwnerSetting] = Field(
        None, alias='GroupOwnerSetting'
    )
    SourcePath: Optional[FieldString] = None


class Logger(BaseModel):
    Component: LoggerComponent
    Id: FieldString
    Level: LoggerLevel
    Space: Optional[FieldInteger] = None
    Type: LoggerType


class ResetDeploymentsRequest(BaseModel):
    Force: Optional[FieldBoolean] = None


class ResetDeploymentsResponse(BaseModel):
    DeploymentArn: Optional[FieldString] = None
    DeploymentId: Optional[FieldString] = None


class ResourceAccessPolicy(BaseModel):
    Permission_1: Optional[Permission] = Field(None, alias='Permission')
    ResourceId: FieldString


class ResourceDownloadOwnerSetting(BaseModel):
    GroupOwner: FieldString
    GroupPermission: Permission


class RuntimeConfiguration(BaseModel):
    TelemetryConfiguration_1: Optional[TelemetryConfiguration] = Field(
        None, alias='TelemetryConfiguration'
    )


class S3MachineLearningModelResourceData(BaseModel):
    DestinationPath: Optional[FieldString] = None
    OwnerSetting: Optional[ResourceDownloadOwnerSetting] = None
    S3Uri: Optional[FieldString] = None


class SageMakerMachineLearningModelResourceData(BaseModel):
    DestinationPath: Optional[FieldString] = None
    OwnerSetting: Optional[ResourceDownloadOwnerSetting] = None
    SageMakerJobArn: Optional[FieldString] = None


class StartBulkDeploymentResponse(BaseModel):
    BulkDeploymentArn: Optional[FieldString] = None
    BulkDeploymentId: Optional[FieldString] = None


class Subscription(BaseModel):
    Id: FieldString
    Source: FieldString
    Subject: FieldString
    Target: FieldString


class Tags(RootModel[Optional[Dict[str, FieldString]]]):
    root: Optional[Dict[str, FieldString]] = None


class UpdateConnectivityInfoResponse(BaseModel):
    Message: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class UpdateConnectorDefinitionRequest(BaseModel):
    Name: Optional[FieldString] = None


class UpdateCoreDefinitionRequest(BaseModel):
    Name: Optional[FieldString] = None


class UpdateDeviceDefinitionRequest(BaseModel):
    Name: Optional[FieldString] = None


class UpdateFunctionDefinitionRequest(BaseModel):
    Name: Optional[FieldString] = None


class UpdateGroupCertificateConfigurationRequest(BaseModel):
    CertificateExpiryInMilliseconds: Optional[FieldString] = None


class UpdateGroupCertificateConfigurationResponse(BaseModel):
    CertificateAuthorityExpiryInMilliseconds: Optional[FieldString] = None
    CertificateExpiryInMilliseconds: Optional[FieldString] = None
    GroupId: Optional[FieldString] = None


class UpdateGroupRequest(BaseModel):
    Name: Optional[FieldString] = None


class UpdateLoggerDefinitionRequest(BaseModel):
    Name: Optional[FieldString] = None


class UpdateResourceDefinitionRequest(BaseModel):
    Name: Optional[FieldString] = None


class UpdateSubscriptionDefinitionRequest(BaseModel):
    Name: Optional[FieldString] = None


class UpdateTargets(RootModel[List[FieldString]]):
    root: List[FieldString] = Field(
        ...,
        description='The ARNs of the targets (IoT things or IoT thing groups) that this update will be applied to.',
    )


class VersionInformation(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class FieldListOfConnectivityInfo(RootModel[List[ConnectivityInfo]]):
    root: List[ConnectivityInfo]


class FieldListOfCore(RootModel[List[Core]]):
    root: List[Core]


class FieldListOfDevice(RootModel[List[Device]]):
    root: List[Device]


class FieldListOfGroupCertificateAuthorityProperties(
    RootModel[List[GroupCertificateAuthorityProperties]]
):
    root: List[GroupCertificateAuthorityProperties]


class FieldListOfGroupInformation(RootModel[List[GroupInformation]]):
    root: List[GroupInformation]


class FieldListOfLogger(RootModel[List[Logger]]):
    root: List[Logger]


class FieldListOfResourceAccessPolicy(RootModel[List[ResourceAccessPolicy]]):
    root: List[ResourceAccessPolicy]


class FieldListOfSubscription(RootModel[List[Subscription]]):
    root: List[Subscription]


class FieldListOfVersionInformation(RootModel[List[VersionInformation]]):
    root: List[VersionInformation]


class FieldListOfString(RootModel[List[FieldString]]):
    root: List[FieldString]


class FieldMapOfString(RootModel[Optional[Dict[str, FieldString]]]):
    root: Optional[Dict[str, FieldString]] = None


class InitialVersion1(BaseModel):
    Cores: Optional[FieldListOfCore] = None


class GreengrassDefinitionCoresPostRequest(BaseModel):
    InitialVersion: Optional[InitialVersion1] = Field(
        None, description='Information about a core definition version.'
    )
    Name: Optional[str] = Field(None, description='The name of the core definition.')
    tags: Optional[Dict[str, FieldString]] = Field(
        None, description='The key-value pair for the resource tag.'
    )


class GreengrassDefinitionCoresCoreDefinitionIdVersionsPostRequest(BaseModel):
    Cores: Optional[List[Core]] = Field(
        None, description='A list of cores in the core definition version.'
    )


class InitialVersion2(BaseModel):
    Devices: Optional[FieldListOfDevice] = None


class GreengrassDefinitionDevicesPostRequest(BaseModel):
    InitialVersion: Optional[InitialVersion2] = Field(
        None, description='Information about a device definition version.'
    )
    Name: Optional[str] = Field(None, description='The name of the device definition.')
    tags: Optional[Dict[str, FieldString]] = Field(
        None, description='The key-value pair for the resource tag.'
    )


class GreengrassDefinitionDevicesDeviceDefinitionIdVersionsPostRequest(BaseModel):
    Devices: Optional[List[Device]] = Field(
        None, description='A list of devices in the definition version.'
    )


class InitialVersion4(BaseModel):
    Loggers: Optional[FieldListOfLogger] = None


class GreengrassDefinitionLoggersPostRequest(BaseModel):
    InitialVersion: Optional[InitialVersion4] = Field(
        None, description='Information about a logger definition version.'
    )
    Name: Optional[str] = Field(None, description='The name of the logger definition.')
    tags: Optional[Dict[str, FieldString]] = Field(
        None, description='The key-value pair for the resource tag.'
    )


class GreengrassDefinitionLoggersLoggerDefinitionIdVersionsPostRequest(BaseModel):
    Loggers: Optional[List[Logger]] = Field(None, description='A list of loggers.')


class InitialVersion6(BaseModel):
    Subscriptions: Optional[FieldListOfSubscription] = None


class GreengrassDefinitionSubscriptionsPostRequest(BaseModel):
    InitialVersion: Optional[InitialVersion6] = Field(
        None, description='Information about a subscription definition version.'
    )
    Name: Optional[str] = Field(
        None, description='The name of the subscription definition.'
    )
    tags: Optional[Dict[str, FieldString]] = Field(
        None, description='The key-value pair for the resource tag.'
    )


class GreengrassDefinitionSubscriptionsSubscriptionDefinitionIdVersionsPostRequest(
    BaseModel
):
    Subscriptions: Optional[List[Subscription]] = Field(
        None, description='A list of subscriptions.'
    )


class GreengrassThingsThingNameConnectivityInfoPutRequest(BaseModel):
    ConnectivityInfo_1: Optional[List[ConnectivityInfo]] = Field(
        None, alias='ConnectivityInfo', description='A list of connectivity info.'
    )


class BulkDeploymentResult(BaseModel):
    CreatedAt: Optional[FieldString] = None
    DeploymentArn: Optional[FieldString] = None
    DeploymentId: Optional[FieldString] = None
    DeploymentStatus: Optional[FieldString] = None
    DeploymentType_1: Optional[DeploymentType] = Field(None, alias='DeploymentType')
    ErrorDetails_1: Optional[ErrorDetails] = Field(None, alias='ErrorDetails')
    ErrorMessage: Optional[FieldString] = None
    GroupArn: Optional[FieldString] = None


class BulkDeploymentResults(RootModel[List[BulkDeploymentResult]]):
    root: List[BulkDeploymentResult]


class Connector(BaseModel):
    ConnectorArn: FieldString
    Id: FieldString
    Parameters: Optional[FieldMapOfString] = None


class CoreDefinitionVersion(BaseModel):
    Cores: Optional[FieldListOfCore] = None


class CreateCoreDefinitionRequest(BaseModel):
    InitialVersion: Optional[CoreDefinitionVersion] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class CreateCoreDefinitionVersionRequest(BaseModel):
    Cores: Optional[FieldListOfCore] = None


class CreateDeviceDefinitionVersionRequest(BaseModel):
    Devices: Optional[FieldListOfDevice] = None


class CreateGroupRequest(BaseModel):
    InitialVersion: Optional[GroupVersion] = None
    Name: FieldString
    tags: Optional[Tags] = None


class CreateLoggerDefinitionVersionRequest(BaseModel):
    Loggers: Optional[FieldListOfLogger] = None


class CreateSoftwareUpdateJobRequest(BaseModel):
    S3UrlSignerRole_1: S3UrlSignerRole = Field(..., alias='S3UrlSignerRole')
    SoftwareToUpdate_1: SoftwareToUpdate = Field(..., alias='SoftwareToUpdate')
    UpdateAgentLogLevel_1: Optional[UpdateAgentLogLevel] = Field(
        None, alias='UpdateAgentLogLevel'
    )
    UpdateTargets_1: UpdateTargets = Field(..., alias='UpdateTargets')
    UpdateTargetsArchitecture_1: UpdateTargetsArchitecture = Field(
        ..., alias='UpdateTargetsArchitecture'
    )
    UpdateTargetsOperatingSystem_1: UpdateTargetsOperatingSystem = Field(
        ..., alias='UpdateTargetsOperatingSystem'
    )


class CreateSubscriptionDefinitionVersionRequest(BaseModel):
    Subscriptions: Optional[FieldListOfSubscription] = None


class DefinitionInformation(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None
    Tags_1: Optional[Tags] = Field(None, alias='Tags')


class DeviceDefinitionVersion(BaseModel):
    Devices: Optional[FieldListOfDevice] = None


class FunctionDefaultExecutionConfig(BaseModel):
    IsolationMode: Optional[FunctionIsolationMode] = None
    RunAs: Optional[FunctionRunAsConfig] = None


class FunctionExecutionConfig(BaseModel):
    IsolationMode: Optional[FunctionIsolationMode] = None
    RunAs: Optional[FunctionRunAsConfig] = None


class GetBulkDeploymentStatusResponse(BaseModel):
    BulkDeploymentMetrics_1: Optional[BulkDeploymentMetrics] = Field(
        None, alias='BulkDeploymentMetrics'
    )
    BulkDeploymentStatus_1: Optional[BulkDeploymentStatus] = Field(
        None, alias='BulkDeploymentStatus'
    )
    CreatedAt: Optional[FieldString] = None
    ErrorDetails_1: Optional[ErrorDetails] = Field(None, alias='ErrorDetails')
    ErrorMessage: Optional[FieldString] = None
    tags: Optional[Tags] = None


class GetConnectivityInfoResponse(BaseModel):
    ConnectivityInfo: Optional[FieldListOfConnectivityInfo] = None
    Message: Optional[FieldString] = None


class GetConnectorDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class GetCoreDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class GetCoreDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Definition: Optional[CoreDefinitionVersion] = None
    Id: Optional[FieldString] = None
    NextToken: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class GetDeviceDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class GetDeviceDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Definition: Optional[DeviceDefinitionVersion] = None
    Id: Optional[FieldString] = None
    NextToken: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class GetFunctionDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class GetGroupResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class GetGroupVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Definition: Optional[GroupVersion] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class GetLoggerDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class GetResourceDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class GetSubscriptionDefinitionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Id: Optional[FieldString] = None
    LastUpdatedTimestamp: Optional[FieldString] = None
    LatestVersion: Optional[FieldString] = None
    LatestVersionArn: Optional[FieldString] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class GetThingRuntimeConfigurationResponse(BaseModel):
    RuntimeConfiguration_1: Optional[RuntimeConfiguration] = Field(
        None, alias='RuntimeConfiguration'
    )


class ListBulkDeploymentDetailedReportsResponse(BaseModel):
    Deployments: Optional[BulkDeploymentResults] = None
    NextToken: Optional[FieldString] = None


class ListConnectorDefinitionVersionsResponse(BaseModel):
    NextToken: Optional[FieldString] = None
    Versions: Optional[FieldListOfVersionInformation] = None


class ListCoreDefinitionVersionsResponse(BaseModel):
    NextToken: Optional[FieldString] = None
    Versions: Optional[FieldListOfVersionInformation] = None


class ListDeviceDefinitionVersionsResponse(BaseModel):
    NextToken: Optional[FieldString] = None
    Versions: Optional[FieldListOfVersionInformation] = None


class ListFunctionDefinitionVersionsResponse(BaseModel):
    NextToken: Optional[FieldString] = None
    Versions: Optional[FieldListOfVersionInformation] = None


class ListGroupCertificateAuthoritiesResponse(BaseModel):
    GroupCertificateAuthorities: Optional[
        FieldListOfGroupCertificateAuthorityProperties
    ] = None


class ListGroupVersionsResponse(BaseModel):
    NextToken: Optional[FieldString] = None
    Versions: Optional[FieldListOfVersionInformation] = None


class ListGroupsResponse(BaseModel):
    Groups: Optional[FieldListOfGroupInformation] = None
    NextToken: Optional[FieldString] = None


class ListLoggerDefinitionVersionsResponse(BaseModel):
    NextToken: Optional[FieldString] = None
    Versions: Optional[FieldListOfVersionInformation] = None


class ListResourceDefinitionVersionsResponse(BaseModel):
    NextToken: Optional[FieldString] = None
    Versions: Optional[FieldListOfVersionInformation] = None


class ListSubscriptionDefinitionVersionsResponse(BaseModel):
    NextToken: Optional[FieldString] = None
    Versions: Optional[FieldListOfVersionInformation] = None


class ListTagsForResourceResponse(BaseModel):
    tags: Optional[Tags] = None


class LoggerDefinitionVersion(BaseModel):
    Loggers: Optional[FieldListOfLogger] = None


class SecretsManagerSecretResourceData(BaseModel):
    ARN: Optional[FieldString] = None
    AdditionalStagingLabelsToDownload: Optional[FieldListOfString] = None


class StartBulkDeploymentRequest(BaseModel):
    ExecutionRoleArn: FieldString
    InputFileUri: FieldString
    tags: Optional[Tags] = None


class SubscriptionDefinitionVersion(BaseModel):
    Subscriptions: Optional[FieldListOfSubscription] = None


class TagResourceRequest(BaseModel):
    tags: Optional[Tags] = None


class UpdateConnectivityInfoRequest(BaseModel):
    ConnectivityInfo: Optional[FieldListOfConnectivityInfo] = None


class FieldListOfConnector(RootModel[List[Connector]]):
    root: List[Connector]


class FieldListOfDefinitionInformation(RootModel[List[DefinitionInformation]]):
    root: List[DefinitionInformation]


class InitialVersion(BaseModel):
    Connectors: Optional[FieldListOfConnector] = None


class GreengrassDefinitionConnectorsPostRequest(BaseModel):
    InitialVersion_1: Optional[InitialVersion] = Field(
        None,
        alias='InitialVersion',
        description='Information about the connector definition version, which is a container for connectors.',
    )
    Name: Optional[str] = Field(
        None, description='The name of the connector definition.'
    )
    tags: Optional[Dict[str, FieldString]] = Field(
        None, description='The key-value pair for the resource tag.'
    )


class GreengrassDefinitionConnectorsConnectorDefinitionIdVersionsPostRequest(BaseModel):
    Connectors: Optional[List[Connector]] = Field(
        None,
        description='A list of references to connectors in this version, with their corresponding configuration settings.',
    )


class DefaultConfig(BaseModel):
    Execution: Optional[FunctionDefaultExecutionConfig] = None


class ConnectorDefinitionVersion(BaseModel):
    Connectors: Optional[FieldListOfConnector] = None


class CreateConnectorDefinitionRequest(BaseModel):
    InitialVersion: Optional[ConnectorDefinitionVersion] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class CreateConnectorDefinitionVersionRequest(BaseModel):
    Connectors: Optional[FieldListOfConnector] = None


class CreateDeviceDefinitionRequest(BaseModel):
    InitialVersion: Optional[DeviceDefinitionVersion] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class CreateLoggerDefinitionRequest(BaseModel):
    InitialVersion: Optional[LoggerDefinitionVersion] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class CreateSubscriptionDefinitionRequest(BaseModel):
    InitialVersion: Optional[SubscriptionDefinitionVersion] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class FunctionConfigurationEnvironment(BaseModel):
    AccessSysfs: Optional[FieldBoolean] = None
    Execution: Optional[FunctionExecutionConfig] = None
    ResourceAccessPolicies: Optional[FieldListOfResourceAccessPolicy] = None
    Variables: Optional[FieldMapOfString] = None


class FunctionDefaultConfig(BaseModel):
    Execution: Optional[FunctionDefaultExecutionConfig] = None


class GetConnectorDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Definition: Optional[ConnectorDefinitionVersion] = None
    Id: Optional[FieldString] = None
    NextToken: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class GetLoggerDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Definition: Optional[LoggerDefinitionVersion] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class GetSubscriptionDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Definition: Optional[SubscriptionDefinitionVersion] = None
    Id: Optional[FieldString] = None
    NextToken: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class ListConnectorDefinitionsResponse(BaseModel):
    Definitions: Optional[FieldListOfDefinitionInformation] = None
    NextToken: Optional[FieldString] = None


class ListCoreDefinitionsResponse(BaseModel):
    Definitions: Optional[FieldListOfDefinitionInformation] = None
    NextToken: Optional[FieldString] = None


class ListDeviceDefinitionsResponse(BaseModel):
    Definitions: Optional[FieldListOfDefinitionInformation] = None
    NextToken: Optional[FieldString] = None


class ListFunctionDefinitionsResponse(BaseModel):
    Definitions: Optional[FieldListOfDefinitionInformation] = None
    NextToken: Optional[FieldString] = None


class ListLoggerDefinitionsResponse(BaseModel):
    Definitions: Optional[FieldListOfDefinitionInformation] = None
    NextToken: Optional[FieldString] = None


class ListResourceDefinitionsResponse(BaseModel):
    Definitions: Optional[FieldListOfDefinitionInformation] = None
    NextToken: Optional[FieldString] = None


class ListSubscriptionDefinitionsResponse(BaseModel):
    Definitions: Optional[FieldListOfDefinitionInformation] = None
    NextToken: Optional[FieldString] = None


class ResourceDataContainer(BaseModel):
    LocalDeviceResourceData_1: Optional[LocalDeviceResourceData] = Field(
        None, alias='LocalDeviceResourceData'
    )
    LocalVolumeResourceData_1: Optional[LocalVolumeResourceData] = Field(
        None, alias='LocalVolumeResourceData'
    )
    S3MachineLearningModelResourceData_1: Optional[
        S3MachineLearningModelResourceData
    ] = Field(None, alias='S3MachineLearningModelResourceData')
    SageMakerMachineLearningModelResourceData_1: Optional[
        SageMakerMachineLearningModelResourceData
    ] = Field(None, alias='SageMakerMachineLearningModelResourceData')
    SecretsManagerSecretResourceData_1: Optional[SecretsManagerSecretResourceData] = (
        Field(None, alias='SecretsManagerSecretResourceData')
    )


class FunctionConfiguration(BaseModel):
    EncodingType_1: Optional[EncodingType] = Field(None, alias='EncodingType')
    Environment: Optional[FunctionConfigurationEnvironment] = None
    ExecArgs: Optional[FieldString] = None
    Executable: Optional[FieldString] = None
    FunctionRuntimeOverride: Optional[FieldString] = None
    MemorySize: Optional[FieldInteger] = None
    Pinned: Optional[FieldBoolean] = None
    Timeout: Optional[FieldInteger] = None


class Resource(BaseModel):
    Id: FieldString
    Name: FieldString
    ResourceDataContainer_1: ResourceDataContainer = Field(
        ..., alias='ResourceDataContainer'
    )


class FieldListOfResource(RootModel[List[Resource]]):
    root: List[Resource]


class InitialVersion5(BaseModel):
    Resources: Optional[FieldListOfResource] = None


class GreengrassDefinitionResourcesPostRequest(BaseModel):
    InitialVersion: Optional[InitialVersion5] = Field(
        None, description='Information about a resource definition version.'
    )
    Name: Optional[str] = Field(
        None, description='The name of the resource definition.'
    )
    tags: Optional[Dict[str, FieldString]] = Field(
        None, description='The key-value pair for the resource tag.'
    )


class GreengrassDefinitionResourcesResourceDefinitionIdVersionsPostRequest(BaseModel):
    Resources: Optional[List[Resource]] = Field(
        None, description='A list of resources.'
    )


class CreateResourceDefinitionVersionRequest(BaseModel):
    Resources: Optional[FieldListOfResource] = None


class Function(BaseModel):
    FunctionArn: Optional[FieldString] = None
    FunctionConfiguration_1: Optional[FunctionConfiguration] = Field(
        None, alias='FunctionConfiguration'
    )
    Id: FieldString


class ResourceDefinitionVersion(BaseModel):
    Resources: Optional[FieldListOfResource] = None


class FieldListOfFunction(RootModel[List[Function]]):
    root: List[Function]


class InitialVersion3(BaseModel):
    DefaultConfig: Optional[FunctionDefaultConfig] = None
    Functions: Optional[FieldListOfFunction] = None


class GreengrassDefinitionFunctionsPostRequest(BaseModel):
    InitialVersion: Optional[InitialVersion3] = Field(
        None, description='Information about a function definition version.'
    )
    Name: Optional[str] = Field(
        None, description='The name of the function definition.'
    )
    tags: Optional[Dict[str, FieldString]] = Field(
        None, description='The key-value pair for the resource tag.'
    )


class GreengrassDefinitionFunctionsFunctionDefinitionIdVersionsPostRequest(BaseModel):
    DefaultConfig_1: Optional[DefaultConfig] = Field(
        None,
        alias='DefaultConfig',
        description='The default configuration that applies to all Lambda functions in the group. Individual Lambda functions can override these settings.',
    )
    Functions: Optional[List[Function]] = Field(
        None,
        description='A list of Lambda functions in this function definition version.',
    )


class CreateFunctionDefinitionVersionRequest(BaseModel):
    DefaultConfig: Optional[FunctionDefaultConfig] = None
    Functions: Optional[FieldListOfFunction] = None


class CreateResourceDefinitionRequest(BaseModel):
    InitialVersion: Optional[ResourceDefinitionVersion] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None


class FunctionDefinitionVersion(BaseModel):
    DefaultConfig: Optional[FunctionDefaultConfig] = None
    Functions: Optional[FieldListOfFunction] = None


class GetFunctionDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Definition: Optional[FunctionDefinitionVersion] = None
    Id: Optional[FieldString] = None
    NextToken: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class GetResourceDefinitionVersionResponse(BaseModel):
    Arn: Optional[FieldString] = None
    CreationTimestamp: Optional[FieldString] = None
    Definition: Optional[ResourceDefinitionVersion] = None
    Id: Optional[FieldString] = None
    Version: Optional[FieldString] = None


class CreateFunctionDefinitionRequest(BaseModel):
    InitialVersion: Optional[FunctionDefinitionVersion] = None
    Name: Optional[FieldString] = None
    tags: Optional[Tags] = None
